// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.1
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /opt/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:1621

#include "LoggerI.h"

// Implementation skeleton constructor
LoggerModule_Logger_i::LoggerModule_Logger_i ()
{
}

// Implementation skeleton destructor
LoggerModule_Logger_i::~LoggerModule_Logger_i ()
{
}

void LoggerModule_Logger_i::log (
  ::LoggerModule::Severity severidade,
  const std::string endereco,
  ::CORBA::UShort pid,
  ::CORBA::ULong hora,
  const std::string msg)
{
  // Add your implementation here
}

::CORBA::Boolean LoggerModule_Logger_i::verbose ()
{
  // Add your implementation here
}

void LoggerModule_Logger_i::verbose (
  ::CORBA::Boolean verbose)
{
  // Add your implementation here
}

